;;; id | path | details importflag | details label | summary import flag | summary label | database import flag | database label (will be used as symbol name for the db)
((1-1-1-1 (FatturaElettronicaHeader DatiTrasmissione IdTrasmittente IdPaese) nil  nil nil nil nil)
 (1-1-1-2 (FatturaElettronicaHeader DatiTrasmissione IdTrasmittente IdCodice) nil  nil nil nil nil)
 (1-1-2 (FatturaElettronicaHeader DatiTrasmissione ProgressivoInvio) nil  nil nil nil nil)
 (1-1-3 (FatturaElettronicaHeader DatiTrasmissione FormatoTrasmissione) nil  nil nil nil nil)
 (1-1-4 (FatturaElettronicaHeader DatiTrasmissione CodiceDestinatario) nil  nil nil nil nil)
 (1-1-5-1 (FatturaElettronicaHeader DatiTrasmissione ContattiTrasmittente Telefono) nil  nil nil nil nil)
 (1-1-5-2 (FatturaElettronicaHeader DatiTrasmissione ContattiTrasmittente Email) nil  nil nil nil nil)
 (1-1-4 (FatturaElettronicaHeader DatiTrasmissione PECDestinatario) nil  nil nil nil nil)
 (1-2-1-1-1 (FatturaElettronicaHeader CedentePrestatore DatiAnagrafici IdFiscaleIVA IdPaese) nil  nil nil nil nil)
 (1-2-1-1-2 (FatturaElettronicaHeader CedentePrestatore DatiAnagrafici IdFiscaleIVA IdCodice) t "IVA cedente" t nil t "seller-tax-id")
 (1-2-1-2 (FatturaElettronicaHeader CedentePrestatore DatiAnagrafici CodiceFiscale) nil "Codice fiscale cedente" nil nil nil nil)
 (1-2-1-3-1 (FatturaElettronicaHeader CedentePrestatore DatiAnagrafici Anagrafica Denominazione) t "Cedente" nil nil t "seller-name")
 (1-2-1-3-2 (FatturaElettronicaHeader CedentePrestatore DatiAnagrafici Anagrafica Nome) nil "Nome cedente" t nil nil nil)
 (1-2-1-3-3 (FatturaElettronicaHeader CedentePrestatore DatiAnagrafici Anagrafica Cognome) nil "Cognome cedente" nil nil nil nil)
 (1-2-1-3-4 (FatturaElettronicaHeader CedentePrestatore DatiAnagrafici Anagrafica Titolo) nil  nil nil nil nil)
 (1-2-1-3-5 (FatturaElettronicaHeader CedentePrestatore DatiAnagrafici Anagrafica CodEORI) nil  nil nil nil nil)
 (1-2-1-4 (FatturaElettronicaHeader CedentePrestatore DatiAnagrafici AlboProfessionale) nil  nil nil nil nil)
 (1-2-1-5 (FatturaElettronicaHeader CedentePrestatore DatiAnagrafici ProvinciaAlbo) nil  nil nil nil nil)
 (1-2-1-6 (FatturaElettronicaHeader CedentePrestatore DatiAnagrafici NumeroIscrizioneAlbo) nil  nil nil nil nil)
 (1-2-1-7 (FatturaElettronicaHeader CedentePrestatore DatiAnagrafici DataIscrizioneAlbo) nil  nil nil nil nil)
 (1-2-1-8 (FatturaElettronicaHeader CedentePrestatore DatiAnagrafici RegimeFiscale) nil  nil nil nil nil)
 (1-2-2-1 (FatturaElettronicaHeader CedentePrestatore Sede Indirizzo) nil  nil nil nil nil)
 (1-2-2-2 (FatturaElettronicaHeader CedentePrestatore Sede NumeroCivico) nil  nil nil nil nil)
 (1-2-2-3 (FatturaElettronicaHeader CedentePrestatore Sede CAP) nil  nil nil nil nil)
 (1-2-2-4 (FatturaElettronicaHeader CedentePrestatore Sede Comune) nil "Comune cedente" nil nil nil nil)
 (1-2-2-5 (FatturaElettronicaHeader CedentePrestatore Sede Provincia) nil  nil nil nil nil)
 (1-2-2-6 (FatturaElettronicaHeader CedentePrestatore Sede Nazione) nil  nil nil nil nil)
 (1-2-3-1 (FatturaElettronicaHeader CedentePrestatore StabileOrganizzazione Indirizzo) nil  nil nil nil nil)
 (1-2-3-2 (FatturaElettronicaHeader CedentePrestatore StabileOrganizzazione NumeroCivico) nil  nil nil nil nil)
 (1-2-3-3 (FatturaElettronicaHeader CedentePrestatore StabileOrganizzazione CAP) nil  nil nil nil nil)
 (1-2-3-4 (FatturaElettronicaHeader CedentePrestatore StabileOrganizzazione Comune) nil  nil nil nil nil)
 (1-2-3-5 (FatturaElettronicaHeader CedentePrestatore StabileOrganizzazione Provincia) nil  nil nil nil nil)
 (1-2-3-6 (FatturaElettronicaHeader CedentePrestatore StabileOrganizzazione Nazione) nil  nil nil nil nil)
 (1-2-4-1 (FatturaElettronicaHeader CedentePrestatore IscrizioneREA Ufficio) nil  nil nil nil nil)
 (1-2-4-2 (FatturaElettronicaHeader CedentePrestatore IscrizioneREA NumeroREA) nil  nil nil nil nil)
 (1-2-4-3 (FatturaElettronicaHeader CedentePrestatore IscrizioneREA CapitaleSociale) nil  nil nil nil nil)
 (1-2-4-4 (FatturaElettronicaHeader CedentePrestatore IscrizioneREA SocioUnico) nil  nil nil nil nil)
 (1-2-4-5 (FatturaElettronicaHeader CedentePrestatore IscrizioneREA StatoLiquidazione) nil  nil nil nil nil)
 (1-2-5-1 (FatturaElettronicaHeader CedentePrestatore Contatti Telefono) nil  nil nil nil nil)
 (1-2-5-2 (FatturaElettronicaHeader CedentePrestatore Contatti Fax) nil  nil nil nil nil)
 (1-2-5-3 (FatturaElettronicaHeader CedentePrestatore Contatti Email) nil  nil nil nil nil)
 (1-2-6 (FatturaElettronicaHeader CedentePrestatore RiferimentoAmministrazione) nil  nil nil nil nil)
 (1-3-1-1-1 (FatturaElettronicaHeader RappresentanteFiscale DatiAnagrafici IdFiscaleIVA IdPaese) nil  nil nil nil nil)
 (1-3-1-1-2 (FatturaElettronicaHeader RappresentanteFiscale DatiAnagrafici IdFiscaleIVA IdCodice) nil  nil nil nil nil)
 (1-3-1-2 (FatturaElettronicaHeader RappresentanteFiscale DatiAnagrafici CodiceFiscale) nil  nil nil nil nil)
 (1-3-1-3-1 (FatturaElettronicaHeader RappresentanteFiscale DatiAnagrafici Anagrafica Denominazione) nil  nil nil nil nil)
 (1-3-1-3-2 (FatturaElettronicaHeader RappresentanteFiscale DatiAnagrafici Anagrafica Nome) nil  nil nil nil nil)
 (1-3-1-3-3 (FatturaElettronicaHeader RappresentanteFiscale DatiAnagrafici Anagrafica Cognome) nil  nil nil nil nil)
 (1-3-1-3-4 (FatturaElettronicaHeader RappresentanteFiscale DatiAnagrafici Anagrafica Titolo) nil  nil nil nil nil)
 (1-3-1-3-5 (FatturaElettronicaHeader RappresentanteFiscale DatiAnagrafici Anagrafica CodEORI) nil  nil nil nil nil)
 (1-4-1-1-1 (FatturaElettronicaHeader CessionarioCommittente DatiAnagrafici IdFiscaleIVA IdPaese) nil  nil nil nil nil)
 (1-4-1-1-2 (FatturaElettronicaHeader CessionarioCommittente DatiAnagrafici IdFiscaleIVA IdCodice) nil "IVA cessionario" nil nil t "buyer-tax-id")
 (1-4-1-2 (FatturaElettronicaHeader CessionarioCommittente DatiAnagrafici CodiceFiscale) nil  nil nil nil nil)
 (1-4-1-3-1 (FatturaElettronicaHeader CessionarioCommittente DatiAnagrafici Anagrafica Denominazione) t "Cessionario" nil nil t "buyer-name")
 (1-4-1-3-2 (FatturaElettronicaHeader CessionarioCommittente DatiAnagrafici Anagrafica Nome) nil  nil nil nil nil)
 (1-4-1-3-3 (FatturaElettronicaHeader CessionarioCommittente DatiAnagrafici Anagrafica Cognome) nil  nil nil nil nil)
 (1-4-1-3-4 (FatturaElettronicaHeader CessionarioCommittente DatiAnagrafici Anagrafica Titolo) nil  nil nil nil nil)
 (1-4-1-3-5 (FatturaElettronicaHeader CessionarioCommittente DatiAnagrafici Anagrafica CodEORI) nil  nil nil nil nil)
 (1-4-2-1 (FatturaElettronicaHeader CessionarioCommittente Sede Indirizzo) nil  nil nil nil nil)
 (1-4-2-2 (FatturaElettronicaHeader CessionarioCommittente Sede NumeroCivico) nil  nil nil nil nil)
 (1-4-2-3 (FatturaElettronicaHeader CessionarioCommittente Sede CAP) nil  nil nil nil nil)
 (1-4-2-4 (FatturaElettronicaHeader CessionarioCommittente Sede Comune) nil "Comune cessionario" nil nil nil nil)
 (1-4-2-5 (FatturaElettronicaHeader CessionarioCommittente Sede Provincia) nil  nil nil nil nil)
 (1-4-2-6 (FatturaElettronicaHeader CessionarioCommittente Sede Nazione) nil  nil nil nil nil)
 (1-4-3-1 (FatturaElettronicaHeader CessionarioCommittente StabileOrganizzazione Indirizzo) nil  nil nil nil nil)
 (1-4-3-2 (FatturaElettronicaHeader CessionarioCommittente StabileOrganizzazione NumeroCivico) nil  nil nil nil nil)
 (1-4-3-3 (FatturaElettronicaHeader CessionarioCommittente StabileOrganizzazione CAP) nil  nil nil nil nil)
 (1-4-3-4 (FatturaElettronicaHeader CessionarioCommittente StabileOrganizzazione Comune) nil  nil nil nil nil)
 (1-4-3-5 (FatturaElettronicaHeader CessionarioCommittente StabileOrganizzazione Provincia) nil  nil nil nil nil)
 (1-4-3-6 (FatturaElettronicaHeader CessionarioCommittente StabileOrganizzazione Nazione) nil  nil nil nil nil)
 (1-4-4-1-1 (FatturaElettronicaHeader CessionarioCommittente RappresentanteFiscale IdFiscaleIVA IdPaese) nil  nil nil nil nil)
 (1-4-4-1-2 (FatturaElettronicaHeader CessionarioCommittente RappresentanteFiscale IdFiscaleIVA IdCodice) nil  nil nil nil nil)
 (1-4-4-2 (FatturaElettronicaHeader CessionarioCommittente RappresentanteFiscale Denominazione) nil  nil nil nil nil)
 (1-4-4-3 (FatturaElettronicaHeader CessionarioCommittente RappresentanteFiscale Nome) nil  nil nil nil nil)
 (1-4-4-4 (FatturaElettronicaHeader CessionarioCommittente RappresentanteFiscale Cognome) nil  nil nil nil nil)
 (1-5-1-1-1 (FatturaElettronicaHeader TerzoIntermediarioOSoggettoEmittente DatiAnagrafici IdFiscaleIVA IdPaese) nil  nil nil nil nil)
 (1-5-1-1-2 (FatturaElettronicaHeader TerzoIntermediarioOSoggettoEmittente DatiAnagrafici IdFiscaleIVA IdCodice) nil  nil nil nil nil)
 (1-5-1-2 (FatturaElettronicaHeader TerzoIntermediarioOSoggettoEmittente DatiAnagrafici CodiceFiscale) nil  nil nil nil nil)
 (1-5-1-3-1 (FatturaElettronicaHeader TerzoIntermediarioOSoggettoEmittente DatiAnagrafici Anagrafica Denominazione) nil  nil nil nil nil)
 (1-5-1-3-2 (FatturaElettronicaHeader TerzoIntermediarioOSoggettoEmittente DatiAnagrafici Anagrafica Nome) nil  nil nil nil nil)
 (1-5-1-3-3 (FatturaElettronicaHeader TerzoIntermediarioOSoggettoEmittente DatiAnagrafici Anagrafica Cognome) nil  nil nil nil nil)
 (1-5-1-3-4 (FatturaElettronicaHeader TerzoIntermediarioOSoggettoEmittente DatiAnagrafici Anagrafica Titolo) nil  nil nil nil nil)
 (1-5-1-3-5 (FatturaElettronicaHeader TerzoIntermediarioOSoggettoEmittente DatiAnagrafici Anagrafica CodEORI) nil  nil nil nil nil)
 (1-6 (FatturaElettronicaHeader SoggettoEmittente) nil  nil nil nil nil)
 (2-1-1-1 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento TipoDocumento) nil  nil nil nil nil)
 (2-1-1-2 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento Divisa) nil  nil nil nil nil)
 (2-1-1-3 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento Data) t "Data documento" t nil t "date")
 (2-1-1-4 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento Numero) t "Numero documento" t nil t "id")
 (2-1-1-5-1 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiRitenuta TipoRitenuta) nil  nil nil nil nil)
 (2-1-1-5-2 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiRitenuta ImportoRitenuta) nil  nil nil nil nil)
 (2-1-1-5-3 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiRitenuta AliquotaRitenuta) nil  nil nil nil nil)
 (2-1-1-5-4 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiRitenuta CausalePagamento) nil  nil nil nil nil)
 (2-1-1-6-1 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiBollo BolloVirtuale) nil  nil nil nil nil)
 (2-1-1-6-2 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiBollo ImportoBollo) nil  nil nil nil nil)
 (2-1-1-7-1 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiCassaPrevidenziale TipoCassa) nil  nil nil nil nil)
 (2-1-1-7-2 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiCassaPrevidenziale AlCassa) nil  nil nil nil nil)
 (2-1-1-7-3 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiCassaPrevidenziale ImportoContributoCassa) nil  nil nil nil nil)
 (2-1-1-7-4 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiCassaPrevidenziale ImponibileCassa) nil  nil nil nil nil)
 (2-1-1-7-5 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiCassaPrevidenziale AliquotaIVA) nil  nil nil nil nil)
 (2-1-1-7-6 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiCassaPrevidenziale Ritenuta) nil  nil nil nil nil)
 (2-1-1-7-7 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiCassaPrevidenziale Natura) nil  nil nil nil nil)
 (2-1-1-7-8 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiCassaPrevidenziale RiferimentoAmministrazione) nil  nil nil nil nil)
 (2-1-1-8-1 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento ScontoMaggiorazione Tipo) nil  nil nil nil nil)
 (2-1-1-8-2 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento ScontoMaggiorazione Percentuale) nil  nil nil nil nil)
 (2-1-1-8-3 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento ScontoMaggiorazione Importo) nil  nil nil nil nil)
 (2-1-1-9 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento ImportoTotaleDocumento) t nil t nil t "payment-amount")
 (2-1-1-10 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento Arrotondamento) nil  nil nil nil nil)
 (2-1-1-11 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento Causale) nil "Causale" nil nil nil nil)
 (2-1-1-12 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento Art73) nil  nil nil nil nil)
 (2-1-2-1 (FatturaElettronicaBody DatiGenerali DatiOrdineAcquisto RiferimentoNumeroLinea) nil  nil nil nil nil)
 (2-1-2-2 (FatturaElettronicaBody DatiGenerali DatiOrdineAcquisto IdDocumento) nil  nil nil nil nil)
 (2-1-2-3 (FatturaElettronicaBody DatiGenerali DatiOrdineAcquisto Data) nil  nil nil nil nil)
 (2-1-2-4 (FatturaElettronicaBody DatiGenerali DatiOrdineAcquisto NumItem) nil  nil nil nil nil)
 (2-1-2-5 (FatturaElettronicaBody DatiGenerali DatiOrdineAcquisto CodiceCommessaConvenzione) nil  nil nil nil nil)
 (2-1-2-6 (FatturaElettronicaBody DatiGenerali DatiOrdineAcquisto CodiceCUP) nil  nil nil nil nil)
 (2-1-2-7 (FatturaElettronicaBody DatiGenerali DatiOrdineAcquisto CodiceCIG) nil  nil nil nil nil)
 (2-1-3 (FatturaElettronicaBody DatiGenerali DatiContratto) nil  nil nil nil nil)
 (2-1-4 (FatturaElettronicaBody DatiGenerali DatiConvenzione) nil  nil nil nil nil)
 (2-1-5 (FatturaElettronicaBody DatiGenerali DatiRicezione) nil  nil nil nil nil)
 (2-1-6 (FatturaElettronicaBody DatiGenerali DatiFattureCollegate) nil  nil nil nil nil)
 (2-1-7-1 (FatturaElettronicaBody DatiGenerali DatiSAL RiferimentoFase) nil  nil nil nil nil)
 (2-1-8-1 (FatturaElettronicaBody DatiGenerali DatiDDT NumeroDDT) nil  nil nil nil nil)
 (2-1-8-2 (FatturaElettronicaBody DatiGenerali DatiDDT DataDDT) nil  nil nil nil nil)
 (2-1-8-3 (FatturaElettronicaBody DatiGenerali DatiDDT RiferimentoNumeroLinea) nil  nil nil nil nil)
 (2-1-9-1-1-1 (FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore IdFiscaleIVA IdPaese) nil  nil nil nil nil)
 (2-1-9-1-1-2 (FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore IdFiscaleIVA IdCodice) nil  nil nil nil nil)
 (2-1-9-1-2 (FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore CodiceFiscale) nil  nil nil nil nil)
 (2-1-9-1-3-1 (FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore Anagrafica Denominazione) nil  nil nil nil nil)
 (2-1-9-1-3-2 (FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore Anagrafica Nome) nil  nil nil nil nil)
 (2-1-9-1-3-3 (FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore Anagrafica Cognome) nil  nil nil nil nil)
 (2-1-9-1-3-4 (FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore Anagrafica Titolo) nil  nil nil nil nil)
 (2-1-9-1-3-5 (FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore Anagrafica CodEORI) nil  nil nil nil nil)
 (2-1-9-1-4 (FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore NumeroLicenzaGuida) nil  nil nil nil nil)
 (2-1-9-2 (FatturaElettronicaBody DatiGenerali DatiSAL MezzoTrasporto) nil  nil nil nil nil)
 (2-1-9-3 (FatturaElettronicaBody DatiGenerali DatiSAL CausaleTrasporto) nil  nil nil nil nil)
 (2-1-9-4 (FatturaElettronicaBody DatiGenerali DatiSAL NumeroColli) nil  nil nil nil nil)
 (2-1-9-5 (FatturaElettronicaBody DatiGenerali DatiSAL Descrizione) nil  nil nil nil nil)
 (2-1-9-6 (FatturaElettronicaBody DatiGenerali DatiSAL UnitaMisuraPeso) nil  nil nil nil nil)
 (2-1-9-7 (FatturaElettronicaBody DatiGenerali DatiSAL PesoLordo) nil  nil nil nil nil)
 (2-1-9-8 (FatturaElettronicaBody DatiGenerali DatiSAL PesoNetto) nil  nil nil nil nil)
 (2-1-9-9 (FatturaElettronicaBody DatiGenerali DatiSAL DataOraRitiro) nil  nil nil nil nil)
 (2-1-9-10 (FatturaElettronicaBody DatiGenerali DatiSAL DataInizioTrasporto) nil  nil nil nil nil)
 (2-1-9-11 (FatturaElettronicaBody DatiGenerali DatiSAL TipoResa) nil  nil nil nil nil)
 (2-1-9-12-1 (FatturaElettronicaBody DatiGenerali DatiSAL IndirizzoResa Indirizzo) nil  nil nil nil nil)
 (2-1-9-12-2 (FatturaElettronicaBody DatiGenerali DatiSAL IndirizzoResa NumeroCivico) nil  nil nil nil nil)
 (2-1-9-12-3 (FatturaElettronicaBody DatiGenerali DatiSAL IndirizzoResa CAP) nil  nil nil nil nil)
 (2-1-9-12-4 (FatturaElettronicaBody DatiGenerali DatiSAL IndirizzoResa Comune) nil  nil nil nil nil)
 (2-1-9-12-5 (FatturaElettronicaBody DatiGenerali DatiSAL IndirizzoResa Provincia) nil  nil nil nil nil)
 (2-1-9-12-6 (FatturaElettronicaBody DatiGenerali DatiSAL IndirizzoResa Nazione) nil  nil nil nil nil)
 (2-1-9-13 (FatturaElettronicaBody DatiGenerali DatiSAL DataOraConsegna) nil  nil nil nil nil)
 (2-1-10-1 (FatturaElettronicaBody DatiGenerali FatturaPrincipale NumeroFatturaPrincipale) nil  nil nil nil nil)
 (2-1-10-2 (FatturaElettronicaBody DatiGenerali FatturaPrincipale DataFatturaPrincipale) nil  nil nil nil nil)
 (2-2-1-1 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee NumeroLinea) t "line-id")
 (2-2-1-2 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee TipoCessionePrestazione) nil  nil nil nil nil)
 (2-2-1-3-1 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee CodiceArticolo CodiceTipo) nil "CodiceTipo" nil nil nil nil)
 (2-2-1-3-2 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee CodiceArticolo CodiceValore) nil "Codice" nil nil nil nil)
 (2-2-1-4 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee Descrizione) t "Desc" nil nil t "line-description")
 (2-2-1-5 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee Quantita) nil  nil nil nil nil)
 (2-2-1-6 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee UnitaMisura) nil  nil nil nil nil)
 (2-2-1-7 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee DataInizioPeriodo) nil  nil nil nil nil)
 (2-2-1-8 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee DataFinePeriodo) nil  nil nil nil nil)
 (2-2-1-9 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee PrezzoUnitario) nil "Prezzo unitario" nil nil nil nil)
 (2-2-1-10-1 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee ScontoMaggiorazione Tipo) nil  nil nil nil nil)
 (2-2-1-10-2 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee ScontoMaggiorazione Percentuale) nil  nil nil nil nil)
 (2-2-1-10-3 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee ScontoMaggiorazione Importo) nil  nil nil nil nil)
 (2-2-1-11 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee PrezzoTotale) t "Prezzo totale" nil nil t "line-unit-taxable-price")
 (2-2-1-12 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee AliquotaIVA) t "Aliquota IVA" nil nil t "line-unit-tax-rate")
 (2-2-1-13 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee Ritenuta) nil  nil nil nil nil)
 (2-2-1-14 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee Natura) nil  nil nil nil nil)
 (2-2-1-15 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee RiferimentoAmministrazione ) nil  nil nil nil nil)
 (2-2-1-16-1 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee AltriDatiGestionali TipoDato) nil  nil nil nil nil)
 (2-2-1-16-2 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee AltriDatiGestionali RiferimentoTesto) nil  nil nil nil nil)
 (2-2-1-16-3 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee AltriDatiGestionali RiferimentoNumero) nil  nil nil nil nil)
 (2-2-1-16-4 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee AltriDatiGestionali RiferimentoData) nil  nil nil nil nil)
 (2-2-2-1 (FatturaElettronicaBody DatiBeniServizi DatiRiepilogo AliquotaIVA) nil  nil nil nil nil)
 (2-2-2-2 (FatturaElettronicaBody DatiBeniServizi DatiRiepilogo Natura) nil  nil nil nil nil)
 (2-2-2-3 (FatturaElettronicaBody DatiBeniServizi DatiRiepilogo SpeseAccessorie) nil  nil nil nil nil)
 (2-2-2-4 (FatturaElettronicaBody DatiBeniServizi DatiRiepilogo Arrotondamento) nil  nil nil nil nil)
 (2-2-2-5 (FatturaElettronicaBody DatiBeniServizi DatiRiepilogo ImponibileImporto) t "Riepilogo Imponibile" t nil t "lines-amount-taxable")
 (2-2-2-6 (FatturaElettronicaBody DatiBeniServizi DatiRiepilogo Imposta) t "Riepilogo Imposta" t nil t "lines-amount-tax")
 (2-2-2-7 (FatturaElettronicaBody DatiBeniServizi DatiRiepilogo EsigibilitaIVA) nil  nil nil nil nil)
 (2-2-2-8 (FatturaElettronicaBody DatiBeniServizi DatiRiepilogo RiferimentoNormativo) nil  nil nil nil nil)
 (2-3-1 (FatturaElettronicaBody DatiVeicoli Data) nil  nil nil nil nil)
 (2-3-2 (FatturaElettronicaBody DatiVeicoli TotalePercorso) nil  nil nil nil nil)
 (2-4-1 (FatturaElettronicaBody DatiPagamento CondizioniPagamento) nil  nil nil nil nil)
 (2-4-2-1 (FatturaElettronicaBody DatiPagamento DettaglioPagamento Beneficiario) nil  nil nil nil nil)
 (2-4-2-2 (FatturaElettronicaBody DatiPagamento DettaglioPagamento ModalitaPagamento) nil "Modalita pagamento" nil nil nil nil)
 (2-4-2-3 (FatturaElettronicaBody DatiPagamento DettaglioPagamento DataRiferimentoTerminiPagamento) nil  nil nil nil nil)
 (2-4-2-4 (FatturaElettronicaBody DatiPagamento DettaglioPagamento GiorniTerminiPagamento) nil  nil nil nil nil)
 (2-4-2-5 (FatturaElettronicaBody DatiPagamento DettaglioPagamento DataScadenzaPagamento) t "Scadenza" t nil t "payment-due-date")
 (2-4-2-6 (FatturaElettronicaBody DatiPagamento DettaglioPagamento ImportoPagamento) nil  nil nil nil nil)
 (2-4-2-7 (FatturaElettronicaBody DatiPagamento DettaglioPagamento CodUfficioPostale) nil  nil nil nil nil)
 (2-4-2-8 (FatturaElettronicaBody DatiPagamento DettaglioPagamento CognomeQuietanzante) nil  nil nil nil nil)
 (2-4-2-9 (FatturaElettronicaBody DatiPagamento DettaglioPagamento NomeQuietanzante) nil  nil nil nil nil)
 (2-4-2-10 (FatturaElettronicaBody DatiPagamento DettaglioPagamento CFQuietanzante) nil  nil nil nil nil)
 (2-4-2-11 (FatturaElettronicaBody DatiPagamento DettaglioPagamento TitoloQuietanzante) nil  nil nil nil nil)
 (2-4-2-12 (FatturaElettronicaBody DatiPagamento DettaglioPagamento IstitutoFinanziario) nil  nil nil nil nil)
 (2-4-2-13 (FatturaElettronicaBody DatiPagamento DettaglioPagamento IBAN) nil  nil nil nil nil)
 (2-4-2-14 (FatturaElettronicaBody DatiPagamento DettaglioPagamento ABI) nil  nil nil nil nil)
 (2-4-2-15 (FatturaElettronicaBody DatiPagamento DettaglioPagamento CAB) nil  nil nil nil nil)
 (2-4-2-16 (FatturaElettronicaBody DatiPagamento DettaglioPagamento BIC) nil  nil nil nil nil)
 (2-4-2-17 (FatturaElettronicaBody DatiPagamento DettaglioPagamento ScontoPagamentoAnticipato) nil  nil nil nil nil)
 (2-4-2-18 (FatturaElettronicaBody DatiPagamento DettaglioPagamento DataLimitePagamentoAnticipato) nil  nil nil nil nil)
 (2-4-2-19 (FatturaElettronicaBody DatiPagamento DettaglioPagamento PenalitaPagamentiRitardati) nil  nil nil nil nil)
 (2-4-2-20 (FatturaElettronicaBody DatiPagamento DettaglioPagamento DataDecorrenzaPenale) nil  nil nil nil nil)
 (2-4-2-21 (FatturaElettronicaBody DatiPagamento DettaglioPagamento CodicePagamento) nil  nil nil nil nil)
 (2-5-1 (FatturaElettronicaBody Allegati NomeAttachment) nil  nil nil nil nil)
 (2-5-2 (FatturaElettronicaBody Allegati AlgoritmoCompressione) nil  nil nil nil nil)
 (2-5-3 (FatturaElettronicaBody Allegati FormatoAttachment) nil  nil nil nil nil)
 (2-5-4 (FatturaElettronicaBody Allegati DescrizioneAttachment) nil  nil nil nil nil)
 (2-5-5 (FatturaElettronicaBody Allegati Attachment) nil  nil nil nil nil))
