;;; id | path | details importflag | details label | summary import flag | summary label | database import flag | database label
((1-2-1-1-2 (FatturaElettronicaHeader CedentePrestatore DatiAnagrafici IdFiscaleIVA IdCodice)
            t "IVA detail" t "IVA summary" t "seller-tax-id")
 (1-2-1-2 (FatturaElettronicaHeader CedentePrestatore DatiAnagrafici CodiceFiscale)
          nil "Codice fiscale cedente" nil nil nil nil)
 (1-2-1-3-1 (FatturaElettronicaHeader CedentePrestatore DatiAnagrafici Anagrafica Denominazione)
            t "Cedente" nil nil t "seller-name")
 (2-1-1-3 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento Data)
          t "Data documento" t nil t "date")
 (2-1-1-4 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento Numero)
          t "Numero documento" t nil t "id")
 (2-1-1-9 (FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento ImportoTotaleDocumento)
          t nil t nil t "payment-amount")
 (2-2-1-1 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee NumeroLinea)
          t "# linea" nil nil t "line-id")
 (2-2-1-4 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee Descrizione)
          t "Desc" nil nil t "line-description")
 (2-2-1-9 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee PrezzoUnitario)
          nil "Prezzo unitario" nil nil nil nil)
 (2-2-1-11 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee PrezzoTotale)
           t "Prezzo totale" nil nil nil nil)
 (2-2-1-12 (FatturaElettronicaBody DatiBeniServizi DettaglioLinee AliquotaIVA)
           t "Aliquota IVA" nil nil nil nil)
 (2-2-2-5 (FatturaElettronicaBody DatiBeniServizi DatiRiepilogo ImponibileImporto)
          nil "Riepilogo Imponibile" nil nil nil nil)
 (2-2-2-6 (FatturaElettronicaBody DatiBeniServizi DatiRiepilogo Imposta)
          nil "Riepilogo Imposta" nil nil nil nil)
 (2-4-2-5 (FatturaElettronicaBody DatiPagamento DettaglioPagamento DataScadenzaPagamento)
          t "Scadenza" t nil t "payment-due-date"))
