((1-1-1-1        '(FatturaElettronicaHeader DatiTrasmissione IdTrasmittente IdPaese))
 (1-1-1-2        '(FatturaElettronicaHeader DatiTrasmissione IdTrasmittente IdCodice))
 (1-1-2          '(FatturaElettronicaHeader DatiTrasmissione ProgressivoInvio))
 (1-1-3          '(FatturaElettronicaHeader DatiTrasmissione FormatoTrasmissione))
 (1-1-4          '(FatturaElettronicaHeader DatiTrasmissione CodiceDestinatario))
 (1-1-5-1        '(FatturaElettronicaHeader DatiTrasmissione ContattiTrasmittente Telefono))
 (1-1-5-2        '(FatturaElettronicaHeader DatiTrasmissione ContattiTrasmittente Email))
 (1-1-4          '(FatturaElettronicaHeader DatiTrasmissione PECDestinatario))
 (1-2-1-1-1      '(FatturaElettronicaHeader CedentePrestatore DatiAnagrafici IdFiscaleIVA IdPaese))
 (1-2-1-1-2      '(FatturaElettronicaHeader CedentePrestatore DatiAnagrafici IdFiscaleIVA IdCodice))
 (1-2-1-2        '(FatturaElettronicaHeader CedentePrestatore DatiAnagrafici CodiceFiscale))
 (1-2-1-3-1      '(FatturaElettronicaHeader CedentePrestatore DatiAnagrafici Anagrafica Denominazione))
 (1-2-1-3-2      '(FatturaElettronicaHeader CedentePrestatore DatiAnagrafici Anagrafica Nome))
 (1-2-1-3-3      '(FatturaElettronicaHeader CedentePrestatore DatiAnagrafici Anagrafica Cognome))
 (1-2-1-3-4      '(FatturaElettronicaHeader CedentePrestatore DatiAnagrafici Anagrafica Titolo))
 (1-2-1-3-5      '(FatturaElettronicaHeader CedentePrestatore DatiAnagrafici Anagrafica CodEORI))
 (1-2-1-4        '(FatturaElettronicaHeader CedentePrestatore DatiAnagrafici AlboProfessionale))
 (1-2-1-5        '(FatturaElettronicaHeader CedentePrestatore DatiAnagrafici ProvinciaAlbo))
 (1-2-1-6        '(FatturaElettronicaHeader CedentePrestatore DatiAnagrafici NumeroIscrizioneAlbo))
 (1-2-1-7        '(FatturaElettronicaHeader CedentePrestatore DatiAnagrafici DataIscrizioneAlbo))
 (1-2-1-8        '(FatturaElettronicaHeader CedentePrestatore DatiAnagrafici RegimeFiscale))
 (1-2-2-1        '(FatturaElettronicaHeader CedentePrestatore Sede Indirizzo))
 (1-2-2-2        '(FatturaElettronicaHeader CedentePrestatore Sede NumeroCivico))
 (1-2-2-3        '(FatturaElettronicaHeader CedentePrestatore Sede CAP))
 (1-2-2-4        '(FatturaElettronicaHeader CedentePrestatore Sede Comune))
 (1-2-2-5        '(FatturaElettronicaHeader CedentePrestatore Sede Provincia))
 (1-2-2-6        '(FatturaElettronicaHeader CedentePrestatore Sede Nazione))
 (1-2-3-1        '(FatturaElettronicaHeader CedentePrestatore StabileOrganizzazione Indirizzo))
 (1-2-3-2        '(FatturaElettronicaHeader CedentePrestatore StabileOrganizzazione NumeroCivico))
 (1-2-3-3        '(FatturaElettronicaHeader CedentePrestatore StabileOrganizzazione CAP))
 (1-2-3-4        '(FatturaElettronicaHeader CedentePrestatore StabileOrganizzazione Comune))
 (1-2-3-5        '(FatturaElettronicaHeader CedentePrestatore StabileOrganizzazione Provincia))
 (1-2-3-6        '(FatturaElettronicaHeader CedentePrestatore StabileOrganizzazione Nazione))
 (1-2-4-1        '(FatturaElettronicaHeader CedentePrestatore IscrizioneREA Ufficio))
 (1-2-4-2        '(FatturaElettronicaHeader CedentePrestatore IscrizioneREA NumeroREA))
 (1-2-4-3        '(FatturaElettronicaHeader CedentePrestatore IscrizioneREA CapitaleSociale))
 (1-2-4-4        '(FatturaElettronicaHeader CedentePrestatore IscrizioneREA SocioUnico))
 (1-2-4-5        '(FatturaElettronicaHeader CedentePrestatore IscrizioneREA StatoLiquidazione))
 (1-2-5-1        '(FatturaElettronicaHeader CedentePrestatore Contatti Telefono))
 (1-2-5-2        '(FatturaElettronicaHeader CedentePrestatore Contatti Fax))
 (1-2-5-3        '(FatturaElettronicaHeader CedentePrestatore Contatti Email))
 (1-2-6          '(FatturaElettronicaHeader CedentePrestatore RiferimentoAmministrazione))
 (1-3-1-1-1      '(FatturaElettronicaHeader RappresentanteFiscale DatiAnagrafici IdFiscaleIVA IdPaese))
 (1-3-1-1-2      '(FatturaElettronicaHeader RappresentanteFiscale DatiAnagrafici IdFiscaleIVA IdCodice))
 (1-3-1-2        '(FatturaElettronicaHeader RappresentanteFiscale DatiAnagrafici CodiceFiscale))
 (1-3-1-3-1      '(FatturaElettronicaHeader RappresentanteFiscale DatiAnagrafici Anagrafica Denominazione))
 (1-3-1-3-2      '(FatturaElettronicaHeader RappresentanteFiscale DatiAnagrafici Anagrafica Nome))
 (1-3-1-3-3      '(FatturaElettronicaHeader RappresentanteFiscale DatiAnagrafici Anagrafica Cognome))
 (1-3-1-3-4      '(FatturaElettronicaHeader RappresentanteFiscale DatiAnagrafici Anagrafica Titolo))
 (1-3-1-3-5      '(FatturaElettronicaHeader RappresentanteFiscale DatiAnagrafici Anagrafica CodEORI))
 (1-4-1-1-1      '(FatturaElettronicaHeader CessionarioCommittente DatiAnagrafici IdFiscaleIVA IdPaese))
 (1-4-1-1-2      '(FatturaElettronicaHeader CessionarioCommittente DatiAnagrafici IdFiscaleIVA IdCodice))
 (1-4-1-2        '(FatturaElettronicaHeader CessionarioCommittente DatiAnagrafici CodiceFiscale))
 (1-4-1-3-1      '(FatturaElettronicaHeader CessionarioCommittente DatiAnagrafici Anagrafica Denominazione))
 (1-4-1-3-2      '(FatturaElettronicaHeader CessionarioCommittente DatiAnagrafici Anagrafica Nome))
 (1-4-1-3-3      '(FatturaElettronicaHeader CessionarioCommittente DatiAnagrafici Anagrafica Cognome))
 (1-4-1-3-4      '(FatturaElettronicaHeader CessionarioCommittente DatiAnagrafici Anagrafica Titolo))
 (1-4-1-3-5      '(FatturaElettronicaHeader CessionarioCommittente DatiAnagrafici Anagrafica CodEORI))
 (1-4-2-1        '(FatturaElettronicaHeader CessionarioCommittente Sede Indirizzo))
 (1-4-2-2        '(FatturaElettronicaHeader CessionarioCommittente Sede NumeroCivico))
 (1-4-2-3        '(FatturaElettronicaHeader CessionarioCommittente Sede CAP))
 (1-4-2-4        '(FatturaElettronicaHeader CessionarioCommittente Sede Comune))
 (1-4-2-5        '(FatturaElettronicaHeader CessionarioCommittente Sede Provincia))
 (1-4-2-6        '(FatturaElettronicaHeader CessionarioCommittente Sede Nazione))
 (1-4-3-1        '(FatturaElettronicaHeader CessionarioCommittente StabileOrganizzazione Indirizzo))
 (1-4-3-2        '(FatturaElettronicaHeader CessionarioCommittente StabileOrganizzazione NumeroCivico))
 (1-4-3-3        '(FatturaElettronicaHeader CessionarioCommittente StabileOrganizzazione CAP))
 (1-4-3-4        '(FatturaElettronicaHeader CessionarioCommittente StabileOrganizzazione Comune))
 (1-4-3-5        '(FatturaElettronicaHeader CessionarioCommittente StabileOrganizzazione Provincia))
 (1-4-3-6        '(FatturaElettronicaHeader CessionarioCommittente StabileOrganizzazione Nazione))
 (1-4-4-1-1      '(FatturaElettronicaHeader CessionarioCommittente RappresentanteFiscale IdFiscaleIVA IdPaese))
 (1-4-4-1-2      '(FatturaElettronicaHeader CessionarioCommittente RappresentanteFiscale IdFiscaleIVA IdCodice))
 (1-4-4-2        '(FatturaElettronicaHeader CessionarioCommittente RappresentanteFiscale Denominazione))
 (1-4-4-3        '(FatturaElettronicaHeader CessionarioCommittente RappresentanteFiscale Nome))
 (1-4-4-4        '(FatturaElettronicaHeader CessionarioCommittente RappresentanteFiscale Cognome))
 (1-5-1-1-1      '(FatturaElettronicaHeader TerzoIntermediarioOSoggettoEmittente DatiAnagrafici IdFiscaleIVA IdPaese))
 (1-5-1-1-2      '(FatturaElettronicaHeader TerzoIntermediarioOSoggettoEmittente DatiAnagrafici IdFiscaleIVA IdCodice))
 (1-5-1-2        '(FatturaElettronicaHeader TerzoIntermediarioOSoggettoEmittente DatiAnagrafici CodiceFiscale))
 (1-5-1-3-1      '(FatturaElettronicaHeader TerzoIntermediarioOSoggettoEmittente DatiAnagrafici Anagrafica Denominazione))
 (1-5-1-3-2      '(FatturaElettronicaHeader TerzoIntermediarioOSoggettoEmittente DatiAnagrafici Anagrafica Nome))
 (1-5-1-3-3      '(FatturaElettronicaHeader TerzoIntermediarioOSoggettoEmittente DatiAnagrafici Anagrafica Cognome))
 (1-5-1-3-4      '(FatturaElettronicaHeader TerzoIntermediarioOSoggettoEmittente DatiAnagrafici Anagrafica Titolo))
 (1-5-1-3-5      '(FatturaElettronicaHeader TerzoIntermediarioOSoggettoEmittente DatiAnagrafici Anagrafica CodEORI))
 (1-6            '(FatturaElettronicaHeader SoggettoEmittente))
 (2-1-1-1        '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento TipoDocumento))
 (2-1-1-2        '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento Divisa))
 (2-1-1-3        '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento Data))
 (2-1-1-4        '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento Numero))
 (2-1-1-5-1      '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiRitenuta TipoRitenuta))
 (2-1-1-5-2      '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiRitenuta ImportoRitenuta))
 (2-1-1-5-3      '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiRitenuta AliquotaRitenuta))
 (2-1-1-5-4      '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiRitenuta CausalePagamento))
 (2-1-1-6-1      '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiBollo BolloVirtuale))
 (2-1-1-6-2      '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiBollo ImportoBollo))
 (2-1-1-7-1      '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiCassaPrevidenziale TipoCassa))
 (2-1-1-7-2      '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiCassaPrevidenziale AlCassa))
 (2-1-1-7-3      '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiCassaPrevidenziale ImportoContributoCassa))
 (2-1-1-7-4      '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiCassaPrevidenziale ImponibileCassa))
 (2-1-1-7-5      '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiCassaPrevidenziale AliquotaIVA))
 (2-1-1-7-6      '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiCassaPrevidenziale Ritenuta))
 (2-1-1-7-7      '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiCassaPrevidenziale Natura))
 (2-1-1-7-8      '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento DatiCassaPrevidenziale RiferimentoAmministrazione))
 (2-1-1-8-1      '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento ScontoMaggiorazione Tipo))
 (2-1-1-8-2      '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento ScontoMaggiorazione Percentuale))
 (2-1-1-8-3      '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento ScontoMaggiorazione Importo))
 (2-1-1-9        '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento ImportoTotaleDocumento))
 (2-1-1-10       '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento Arrotondamento))
 (2-1-1-11       '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento Causale))
 (2-1-1-12       '(FatturaElettronicaBody DatiGenerali DatiGeneraliDocumento Art73))
 (2-1-2-1        '(FatturaElettronicaBody DatiGenerali DatiOrdineAcquisto RiferimentoNumeroLinea))
 (2-1-2-2        '(FatturaElettronicaBody DatiGenerali DatiOrdineAcquisto IdDocumento))
 (2-1-2-3        '(FatturaElettronicaBody DatiGenerali DatiOrdineAcquisto Data))
 (2-1-2-4        '(FatturaElettronicaBody DatiGenerali DatiOrdineAcquisto NumItem))
 (2-1-2-5        '(FatturaElettronicaBody DatiGenerali DatiOrdineAcquisto CodiceCommessaConvenzione))
 (2-1-2-6        '(FatturaElettronicaBody DatiGenerali DatiOrdineAcquisto CodiceCUP))
 (2-1-2-7        '(FatturaElettronicaBody DatiGenerali DatiOrdineAcquisto CodiceCIG))
 (2-1-3          '(FatturaElettronicaBody DatiGenerali DatiContratto))
 (2-1-4          '(FatturaElettronicaBody DatiGenerali DatiConvenzione))
 (2-1-5          '(FatturaElettronicaBody DatiGenerali DatiRicezione))
 (2-1-6          '(FatturaElettronicaBody DatiGenerali DatiFattureCollegate))
 (2-1-7-1        '(FatturaElettronicaBody DatiGenerali DatiSAL RiferimentoFase))
 (2-1-8-1        '(FatturaElettronicaBody DatiGenerali DatiDDT NumeroDDT))
 (2-1-8-2        '(FatturaElettronicaBody DatiGenerali DatiDDT DataDDT))
 (2-1-8-3        '(FatturaElettronicaBody DatiGenerali DatiDDT RiferimentoNumeroLinea))
 (2-1-9-1-1-1    '(FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore IdFiscaleIVA IdPaese))
 (2-1-9-1-1-2    '(FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore IdFiscaleIVA IdCodice))
 (2-1-9-1-2      '(FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore CodiceFiscale))
 (2-1-9-1-3-1    '(FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore Anagrafica Denominazione))
 (2-1-9-1-3-2    '(FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore Anagrafica Nome))
 (2-1-9-1-3-3    '(FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore Anagrafica Cognome))
 (2-1-9-1-3-4    '(FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore Anagrafica Titolo))
 (2-1-9-1-3-5    '(FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore Anagrafica CodEORI))
 (2-1-9-1-4      '(FatturaElettronicaBody DatiGenerali DatiTrasporto DatiAnagraficiVettore NumeroLicenzaGuida))
 (2-1-9-2        '(FatturaElettronicaBody DatiGenerali DatiSAL MezzoTrasporto))
 (2-1-9-3        '(FatturaElettronicaBody DatiGenerali DatiSAL CausaleTrasporto))
 (2-1-9-4        '(FatturaElettronicaBody DatiGenerali DatiSAL NumeroColli))
 (2-1-9-5        '(FatturaElettronicaBody DatiGenerali DatiSAL Descrizione))
 (2-1-9-6        '(FatturaElettronicaBody DatiGenerali DatiSAL UnitaMisuraPeso))
 (2-1-9-7        '(FatturaElettronicaBody DatiGenerali DatiSAL PesoLordo))
 (2-1-9-8        '(FatturaElettronicaBody DatiGenerali DatiSAL PesoNetto))
 (2-1-9-9        '(FatturaElettronicaBody DatiGenerali DatiSAL DataOraRitiro))
 (2-1-9-10       '(FatturaElettronicaBody DatiGenerali DatiSAL DataInizioTrasporto))
 (2-1-9-11       '(FatturaElettronicaBody DatiGenerali DatiSAL TipoResa))
 (2-1-9-12-1     '(FatturaElettronicaBody DatiGenerali DatiSAL IndirizzoResa Indirizzo))
 (2-1-9-12-2     '(FatturaElettronicaBody DatiGenerali DatiSAL IndirizzoResa NumeroCivico))
 (2-1-9-12-3     '(FatturaElettronicaBody DatiGenerali DatiSAL IndirizzoResa CAP))
 (2-1-9-12-4     '(FatturaElettronicaBody DatiGenerali DatiSAL IndirizzoResa Comune))
 (2-1-9-12-5     '(FatturaElettronicaBody DatiGenerali DatiSAL IndirizzoResa Provincia))
 (2-1-9-12-6     '(FatturaElettronicaBody DatiGenerali DatiSAL IndirizzoResa Nazione))
 (2-1-9-13       '(FatturaElettronicaBody DatiGenerali DatiSAL DataOraConsegna))
 (2-1-10-1       '(FatturaElettronicaBody DatiGenerali FatturaPrincipale NumeroFatturaPrincipale))
 (2-1-10-2       '(FatturaElettronicaBody DatiGenerali FatturaPrincipale DataFatturaPrincipale))
 (2-2-1-1        '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee NumeroLinea))
 (2-2-1-2        '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee TipoCessionePrestazione))
 (2-2-1-3-1      '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee CodiceArticolo CodiceTipo))
 (2-2-1-3-2      '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee CodiceArticolo CodiceValore))
 (2-2-1-4        '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee Descrizione))
 (2-2-1-5        '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee Quantita))
 (2-2-1-6        '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee UnitaMisura))
 (2-2-1-7        '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee DataInizioPeriodo))
 (2-2-1-8        '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee DataFinePeriodo))
 (2-2-1-9        '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee PrezzoUnitario))
 (2-2-1-10-1     '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee ScontoMaggiorazione Tipo))
 (2-2-1-10-2     '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee ScontoMaggiorazione Percentuale))
 (2-2-1-10-3     '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee ScontoMaggiorazione Importo))
 (2-2-1-11       '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee PrezzoTotale ))
 (2-2-1-12       '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee AliquotaIVA ))
 (2-2-1-13       '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee Ritenuta ))
 (2-2-1-14       '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee Natura ))
 (2-2-1-15       '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee RiferimentoAmministrazione ))
 (2-2-1-16-1     '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee AltriDatiGestionali TipoDato))
 (2-2-1-16-2     '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee AltriDatiGestionali RiferimentoTesto))
 (2-2-1-16-3     '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee AltriDatiGestionali RiferimentoNumero))
 (2-2-1-16-4     '(FatturaElettronicaBody DatiBeniServizi DettaglioLinee AltriDatiGestionali RiferimentoData))
 (2-2-2-1        '(FatturaElettronicaBody DatiBeniServizi DatiRiepilogo AliquotaIVA))
 (2-2-2-2        '(FatturaElettronicaBody DatiBeniServizi DatiRiepilogo Natura))
 (2-2-2-3        '(FatturaElettronicaBody DatiBeniServizi DatiRiepilogo SpeseAccessorie))
 (2-2-2-4        '(FatturaElettronicaBody DatiBeniServizi DatiRiepilogo Arrotondamento))
 (2-2-2-5        '(FatturaElettronicaBody DatiBeniServizi DatiRiepilogo ImponibileImporto))
 (2-2-2-6        '(FatturaElettronicaBody DatiBeniServizi DatiRiepilogo Imposta))
 (2-2-2-7        '(FatturaElettronicaBody DatiBeniServizi DatiRiepilogo EsigibilitaIVA))
 (2-2-2-8        '(FatturaElettronicaBody DatiBeniServizi DatiRiepilogo RiferimentoNormativo))
 (2-3-1          '(FatturaElettronicaBody DatiVeicoli Data))
 (2-3-2          '(FatturaElettronicaBody DatiVeicoli TotalePercorso))
 (2-4-1          '(FatturaElettronicaBody DatiPagamento CondizioniPagamento))
 (2-4-2-1        '(FatturaElettronicaBody DatiPagamento DettaglioPagamento Beneficiario))
 (2-4-2-2        '(FatturaElettronicaBody DatiPagamento DettaglioPagamento ModalitaPagamento))
 (2-4-2-3        '(FatturaElettronicaBody DatiPagamento DettaglioPagamento DataRiferimentoTerminiPagamento))
 (2-4-2-4        '(FatturaElettronicaBody DatiPagamento DettaglioPagamento GiorniTerminiPagamento))
 (2-4-2-5        '(FatturaElettronicaBody DatiPagamento DettaglioPagamento DataScadenzaPagamento))
 (2-4-2-6        '(FatturaElettronicaBody DatiPagamento DettaglioPagamento ImportoPagamento))
 (2-4-2-7        '(FatturaElettronicaBody DatiPagamento DettaglioPagamento CodUfficioPostale))
 (2-4-2-8        '(FatturaElettronicaBody DatiPagamento DettaglioPagamento CognomeQuietanzante))
 (2-4-2-9        '(FatturaElettronicaBody DatiPagamento DettaglioPagamento NomeQuietanzante))
 (2-4-2-10       '(FatturaElettronicaBody DatiPagamento DettaglioPagamento CFQuietanzante))
 (2-4-2-11       '(FatturaElettronicaBody DatiPagamento DettaglioPagamento TitoloQuietanzante))
 (2-4-2-12       '(FatturaElettronicaBody DatiPagamento DettaglioPagamento IstitutoFinanziario))
 (2-4-2-13       '(FatturaElettronicaBody DatiPagamento DettaglioPagamento IBAN))
 (2-4-2-14       '(FatturaElettronicaBody DatiPagamento DettaglioPagamento ABI))
 (2-4-2-15       '(FatturaElettronicaBody DatiPagamento DettaglioPagamento CAB))
 (2-4-2-16       '(FatturaElettronicaBody DatiPagamento DettaglioPagamento BIC))
 (2-4-2-17       '(FatturaElettronicaBody DatiPagamento DettaglioPagamento ScontoPagamentoAnticipato))
 (2-4-2-18       '(FatturaElettronicaBody DatiPagamento DettaglioPagamento DataLimitePagamentoAnticipato))
 (2-4-2-19       '(FatturaElettronicaBody DatiPagamento DettaglioPagamento PenalitaPagamentiRitardati))
 (2-4-2-20       '(FatturaElettronicaBody DatiPagamento DettaglioPagamento DataDecorrenzaPenale))
 (2-4-2-21       '(FatturaElettronicaBody DatiPagamento DettaglioPagamento CodicePagamento))
 (2-5-1          '(FatturaElettronicaBody Allegati NomeAttachment))
 (2-5-2          '(FatturaElettronicaBody Allegati AlgoritmoCompressione))
 (2-5-3          '(FatturaElettronicaBody Allegati FormatoAttachment))
 (2-5-4          '(FatturaElettronicaBody Allegati DescrizioneAttachment))
 (2-5-5          '(FatturaElettronicaBody Allegati Attachment)))

;; ("root" "FatturaElettronica"
;;  (("1" "FatturaElettronicaHeader"
;;    (("1.1" "DatiTrasmissione"
;;      (("1.1.1" "IdTrasmittente"
;;        (("1.1.1.1" "IdPaese" nil)
;;         ("1.1.1.2" "IdCodice" nil)))
;;       ("1.1.2" "ProgressivoInvio" nil)
;;       ("1.1.3" "FormatoTrasmissione" nil)
;;       ("1.1.4" "CodiceDestinatario" nil)
;;       ("1.1.5" "ContattiTrasmittente"
;;        (("1.1.5.1" "Telefono" nil)
;;         ("1.1.5.2" "Email" nil)))
;;       ("1.1.6" "PECDestinatario" nil)))
;;     ("1.2" "CedentePrestatore"
;;      (("1.2.1" "DatiAnagrafici"
;;        (("1.2.1.1" "IdFiscaleIVA"
;;          (("1.2.1.1.1" "IdPaese" nil)
;;           ("1.2.1.1.2" "IdCodice" nil)))
;;         ("1.2.1.2" "CodiceFiscale" nil)
;;         ("1.2.1.3" "Anagrafica"
;;          (("1.2.1.3.1" "Denominazione" nil)
;;           ("1.2.1.3.2" "Nome" nil)
;;           ("1.2.1.3.3" "Cognome" nil)
;;           ("1.2.1.3.4" "Titolo" nil)
;;           ("1.2.1.3.5" "CodEORI" nil)))
;;         ("1.2.1.4" "AlboProfessionale" nil)
;;         ("1.2.1.5" "ProvinciaAlbo" nil)
;;         ("1.2.1.6" "NumeroIscrizioneAlbo" nil)
;;         ("1.2.1.7" "DataIscrizioneAlbo" nil)
;;         ("1.2.1.8" "RegimeFiscale" nil)))
;;       ("1.2.2" "Sede"
;;        (("1.2.2.1" "Indirizzo" nil)
;;         ("1.2.2.2" "NumeroCivico" nil)
;;         ("1.2.2.3" "CAP" nil)
;;         ("1.2.2.4" "Comune" nil)
;;         ("1.2.2.5" "Provincia" nil)
;;         ("1.2.2.6" "Nazione" nil)))
;;       ("1.2.3" "StabileOrganizzazione"
;;        (("1.2.3.1" "Indirizzo" nil)
;;         ("1.2.3.2" "NumeroCivico" nil)
;;         ("1.2.3.3" "CAP" nil)
;;         ("1.2.3.4" "Comune" nil)
;;         ("1.2.3.5" "Provincia" nil)
;;         ("1.2.3.6" "Nazione" nil)))
;;       ("1.2.4" "IscrizioneREA"
;;        (("1.2.4.1" "Ufficio" nil)
;;         ("1.2.4.2" "NumeroREA" nil)
;;         ("1.2.4.3" "CapitaleSociale" nil)
;;         ("1.2.4.4" "SocioUnico" nil)
;;         ("1.2.4.5" "StatoLiquidazione" nil)))
;;       ("1.2.5" "Contatti"
;;        (("1.2.5.1" "Telefono" nil)
;;         ("1.2.5.2" "Fax" nil)
;;         ("1.2.5.3" "Email" nil)))
;;       ("1.2.6" "RiferimentoAmministrazione" nil)))
;;     ("1.3" "RappresentanteFiscale"
;;      (("1.3.1" "DatiAnagrafici"
;;        (("1.3.1.1" "IdFiscaleIVA"
;;          (("1.3.1.1.1" "IdPaese" nil)
;;           ("1.3.1.1.2" "IdCodice" nil)))
;;         ("1.3.1.2" "CodiceFiscale" nil)
;;         ("1.3.1.3" "Anagrafica"
;;          (("1.3.1.3.1" "Denominazione" nil)
;;           ("1.3.1.3.2" "Nome" nil)
;;           ("1.3.1.3.3" "Cognome" nil)
;;           ("1.3.1.3.4" "Titolo" nil)
;;           ("1.3.1.3.5" "CodEORI" nil)))))))
;;     ("1.4" "CessionarioCommittente"
;;      (("1.4.1" "DatiAnagrafici"
;;        (("1.4.1.1" "IdFiscaleIVA"
;;          (("1.4.1.1.1" "IdPaese" nil)
;;           ("1.4.1.1.2" "IdCodice" nil)))
;;         ("1.4.1.2" "CodiceFiscale" nil)
;;         ("1.4.1.3" "Anagrafica"
;;          (("1.4.1.3.1" "Denominazione" nil)
;;           ("1.4.1.3.2" "Nome" nil)
;;           ("1.4.1.3.3" "Cognome" nil)
;;           ("1.4.1.3.4" "Titolo" nil)
;;           ("1.4.1.3.5" "CodEORI" nil)))))
;;       ("1.4.2" "Sede"
;;        (("1.4.2.1" "Indirizzo" nil)
;;         ("1.4.2.2" "NumeroCivico" nil)
;;         ("1.4.2.3" "CAP" nil)
;;         ("1.4.2.4" "Comune" nil)
;;         ("1.4.2.5" "Provincia" nil)
;;         ("1.4.2.6" "Nazione" nil)))
;;       ("1.4.3" "StabileOrganizzazione"
;;        (("1.4.3.1" "Indirizzo" nil)
;;         ("1.4.3.2" "NumeroCivico" nil)
;;         ("1.4.3.3" "CAP" nil)
;;         ("1.4.3.4" "Comune" nil)
;;         ("1.4.3.5" "Provincia" nil)
;;         ("1.4.3.6" "Nazione" nil)))
;;       ("1.4.4" "RappresentanteFiscale"
;;        (("1.4.4.1" "IdFiscaleIVA"
;;          (("1.4.4.1.1" "IdPaese" nil)
;;           ("1.4.4.1.2" "IdCodice" nil)))
;;         ("1.4.4.2" "Denominazione" nil)
;;         ("1.4.4.3" "Nome" nil)
;;         ("1.4.4.4" "Cognome" nil)))))
;;     ("1.5" "TerzoIntermediarioOSoggettoEmittente"
;;      (("1.5.1" "DatiAnagrafici"
;;        (("1.5.1.1" "IdFiscaleIVA"
;;          (("1.5.1.1.1" "IdPaese" nil)
;;           ("1.5.1.1.2" "IdCodice" nil)))
;;         ("1.5.1.2" "CodiceFiscale" nil)
;;         ("1.5.1.3" "Anagrafica"
;;          (("1.5.1.3.1" "Denominazione" nil)
;;           ("1.5.1.3.2" "Nome" nil)
;;           ("1.5.1.3.3" "Cognome" nil)
;;           ("1.5.1.3.4" "Titolo" nil)
;;           ("1.5.1.3.5" "CodEORI" nil)))))))
;;     ("1.6" "SoggettoEmittente" nil)))
;;   ("2"  multi "FatturaElettronicaBody"
;;    (("2.1" "DatiGenerali"
;;      (("2.1.1" "DatiGeneraliDocumento"
;;        (("2.1.1.1" "TipoDocumento" nil)
;;         ("2.1.1.2" "Divisa" nil)
;;         ("2.1.1.3" "Data" nil)
;;         ("2.1.1.4" "Numero" nil)
;;         ("2.1.1.5" "DatiRitenuta"
;;          (("2.1.1.5.1" "TipoRitenuta" nil)
;;           ("2.1.1.5.2" "ImportoRitenuta" nil)
;;           ("2.1.1.5.3" "AliquotaRitenuta" nil)
;;           ("2.1.1.5.4" "CausalePagamento" nil)))
;;         ("2.1.1.6" "DatiBollo"
;;          (("2.1.1.6.1" "BolloVirtuale" nil)
;;           ("2.1.1.6.2" "ImportoBollo" nil)))
;;         ("2.1.1.7" "DatiCassaPrevidenziale"
;;          (("2.1.1.7.1" "TipoCassa" nil)
;;           ("2.1.1.7.2" "AlCassa" nil)
;;           ("2.1.1.7.3" "ImportoContributoCassa" nil)
;;           ("2.1.1.7.4" "ImponibileCassa" nil)
;;           ("2.1.1.7.5" "AliquotaIVA" nil)
;;           ("2.1.1.7.6" "Ritenuta" nil)
;;           ("2.1.1.7.7" "Natura" nil)
;;           ("2.1.1.7.8" "RiferimentoAmministrazione" nil)))
;;         ("2.1.1.8" "ScontoMaggiorazione"
;;          (("2.1.1.8.1" "Tipo" nil)
;;           ("2.1.1.8.2" "Percentuale" nil)
;;           ("2.1.1.8.3" "Importo" nil)))
;;         ("2.1.1.9" "ImportoTotaleDocumento" nil)
;;         ("2.1.1.10" "Arrotondamento" nil)
;;         ("2.1.1.11" "Causale" nil)
;;         ("2.1.1.12" "Art73" nil)))
;;       ("2.1.2" "DatiOrdineAcquisto"
;;        (("2.1.2.1" "RiferimentoNumeroLinea" nil)
;;         ("2.1.2.2" "IdDocumento" nil)
;;         ("2.1.2.3" "Data" nil)
;;         ("2.1.2.4" "NumItem" nil)
;;         ("2.1.2.5" "CodiceCommessaConvenzione" nil)
;;         ("2.1.2.6" "CodiceCUP" nil)
;;         ("2.1.2.7" "CodiceCIG" nil)))
;;       ("2.1.3" "DatiContratto" nil)
;;       ("2.1.4" "DatiConvenzione" nil)
;;       ("2.1.5" "DatiRicezione" nil)
;;       ("2.1.6" "DatiFattureCollegate" nil)
;;       ("2.1.7" "DatiSAL"
;;        (("2.1.7.1" "RiferimentoFase" nil)))
;;       ("2.1.8" "DatiDDT"
;;        (("2.1.8.1" "NumeroDDT" nil)
;;         ("2.1.8.2" "DataDDT" nil)
;;         ("2.1.8.3" "RiferimentoNumeroLinea" nil)))
;;       ("2.1.9" "DatiTrasporto"
;;        (("2.1.9.1" "DatiAnagraficiVettore"
;;          (("2.1.9.1.1" "IdFiscaleIVA"
;;            (("2.1.9.1.1.1" "IdPaese" nil)
;;             ("2.1.9.1.1.2" "IdCodice" nil)))
;;           ("2.1.9.1.2" "CodiceFiscale" nil)
;;           ("2.1.9.1.3" "Anagrafica"
;;            (("2.1.9.1.3.1" "Denominazione" nil)
;;             ("2.1.9.1.3.2" "Nome" nil)
;;             ("2.1.9.1.3.3" "Cognome" nil)
;;             ("2.1.9.1.3.4" "Titolo" nil)
;;             ("2.1.9.1.3.5" "CodEORI" nil)))
;;           ("2.1.9.1.4" "NumeroLicenzaGuida" nil)))
;;         ("2.1.9.2" "MezzoTrasporto" nil)
;;         ("2.1.9.3" "CausaleTrasporto" nil)
;;         ("2.1.9.4" "NumeroColli" nil)
;;         ("2.1.9.5" "Descrizione" nil)
;;         ("2.1.9.6" "UnitaMisuraPeso" nil)
;;         ("2.1.9.7" "PesoLordo" nil)
;;         ("2.1.9.8" "PesoNetto" nil)
;;         ("2.1.9.9" "DataOraRitiro" nil)
;;         ("2.1.9.10" "DataInizioTrasporto" nil)
;;         ("2.1.9.11" "TipoResa" nil)
;;         ("2.1.9.12" "IndirizzoResa"
;;          (("2.1.9.12.1" "Indirizzo" nil)
;;           ("2.1.9.12.2" "NumeroCivico" nil)
;;           ("2.1.9.12.3" "CAP" nil)
;;           ("2.1.9.12.4" "Comune" nil)
;;           ("2.1.9.12.5" "Provincia" nil)
;;           ("2.1.9.12.6" "Nazione" nil)))
;;         ("2.1.9.13" "DataOraConsegna" nil)))
;;       ("2.1.10" "FatturaPrincipale"
;;        (("2.1.10.1" "NumeroFatturaPrincipale" nil)
;;         ("2.1.10.2" "DataFatturaPrincipale" nil)))))
;;     ("2.2" "DatiBeniServizi"
;;      (("2.2.1"  multi "DettaglioLinee"
;;        (("2.2.1.1" "NumeroLinea" nil)
;;         ("2.2.1.2" "TipoCessionePrestazione" nil)
;;         ("2.2.1.3" "CodiceArticolo"
;;          (("2.2.1.3.1" "CodiceTipo" nil)
;;           ("2.2.1.3.2" "CodiceValore" nil)))
;;         ("2.2.1.4" "Descrizione" nil)
;;         ("2.2.1.5" "Quantita" nil)
;;         ("2.2.1.6" "UnitaMisura" nil)
;;         ("2.2.1.7" "DataInizioPeriodo" nil)
;;         ("2.2.1.8" "DataFinePeriodo" nil)
;;         ("2.2.1.9" "PrezzoUnitario" nil)
;;         ("2.2.1.10" "ScontoMaggiorazione"
;;          (("2.2.1.10.1" "Tipo" nil)
;;           ("2.2.1.10.2" "Percentuale" nil)
;;           ("2.2.1.10.3" "Importo" nil)))
;;         ("2.2.1.11" "PrezzoTotale" nil)
;;         ("2.2.1.12" "AliquotaIVA" nil)
;;         ("2.2.1.13" "Ritenuta" nil)
;;         ("2.2.1.14" "Natura" nil)
;;         ("2.2.1.15" "RiferimentoAmministrazione" nil)
;;         ("2.2.1.16" "AltriDatiGestionali"
;;          (("2.2.1.16.1" "TipoDato" nil)
;;           ("2.2.1.16.2" "RiferimentoTesto" nil)
;;           ("2.2.1.16.3" "RiferimentoNumero" nil)
;;           ("2.2.1.16.4" "RiferimentoData" nil)))))
;;       ("2.2.2" "DatiRiepilogo"
;;        (("2.2.2.1" "AliquotaIVA" nil)
;;         ("2.2.2.2" "Natura" nil)
;;         ("2.2.2.3" "SpeseAccessorie" nil)
;;         ("2.2.2.4" "Arrotondamento" nil)
;;         ("2.2.2.5" "ImponibileImporto" nil)
;;         ("2.2.2.6" "Imposta" nil)
;;         ("2.2.2.7" "EsigibilitaIVA" nil)
;;         ("2.2.2.8" "RiferimentoNormativo" nil)))))
;;     ("2.3" "DatiVeicoli"
;;      (("2.3.1" "Data" nil)
;;       ("2.3.2" "TotalePercorso" nil)))
;;     ("2.4" "DatiPagamento"
;;      (("2.4.1" "CondizioniPagamento" nil)
;;       ("2.4.2" "DettaglioPagamento"
;;        (("2.4.2.1" "Beneficiario" nil)
;;         ("2.4.2.2" "ModalitaPagamento" nil)
;;         ("2.4.2.3" "DataRiferimentoTerminiPagamento" nil)
;;         ("2.4.2.4" "GiorniTerminiPagamento" nil)
;;         ("2.4.2.5" "DataScadenzaPagamento" nil)
;;         ("2.4.2.6" "ImportoPagamento" nil)
;;         ("2.4.2.7" "CodUfficioPostale" nil)
;;         ("2.4.2.8" "CognomeQuietanzante" nil)
;;         ("2.4.2.9" "NomeQuietanzante" nil)
;;         ("2.4.2.10" "CFQuietanzante" nil)
;;         ("2.4.2.11" "TitoloQuietanzante" nil)
;;         ("2.4.2.12" "IstitutoFinanziario" nil)
;;         ("2.4.2.13" "IBAN" nil)
;;         ("2.4.2.14" "ABI" nil)
;;         ("2.4.2.15" "CAB" nil)
;;         ("2.4.2.16" "BIC" nil)
;;         ("2.4.2.17" "ScontoPagamentoAnticipato" nil)
;;         ("2.4.2.18" "DataLimitePagamentoAnticipato" nil)
;;         ("2.4.2.19" "PenalitaPagamentiRitardati" nil)
;;         ("2.4.2.20" "DataDecorrenzaPenale" nil)
;;         ("2.4.2.21" "CodicePagamento" nil)))))
;;     ("2.5" "Allegati"
;;      (("2.5.1" "NomeAttachment" nil)
;;       ("2.5.2" "AlgoritmoCompressione" nil)
;;       ("2.5.3" "FormatoAttachment" nil)
;;       ("2.5.4" "DescrizioneAttachment" nil)
;;       ("2.5.5" "Attachment" nil)))))))
